### ISSUE TITLE
Simplify: db calls

### ISSUE THREAD

**Issue by blerude** [GoodMattwin/expresso#2]
https://github.com/GoodMattwin/expresso/blob/master/api/employees.js#L52-L53

This format is a bit difficult to parse through. Try setting the sql call and the values as variables so that the call itself is cleaner, like this: 

```
const sql = `INSERT INTO Employee (name, position, wage, is_current_employee) 
                 VALUES ($name, $position, $wage, $isCurrentEmployee)`;
const values = {
      $name: name,
      $position: position,
      $wage: wage,
      $isCurrentEmployee: isCurrentEmployee
};
```

**Comment by GoodMattwin** [comment]
Good thought.  I was so excited to realize template literals worked in db calls that I may have overdone it :)
