### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [GoodMattwin/expresso#4]
Grade: Exceeds Expectations

Awesome job on this project! You completed all the necessary pieces to the assignment, and you have a great handle for how to write routes in JavaScript. Your code is well organized and easy to read, and your reading/writing to and from the SQL database is well orchestrated. The logic behind your routes is rock solid, and you do a great job handling errors and sending status codes when necessary.

Moving forward, I encourage you to focus on some of the minor details that can make your code more readable. For example, start getting in the habit of leaving comments that provide insight into the purpose of each route or section of code. Also, paying attention to how long or clunky certain lines are (like you db function calls) can lead you to finding cleaner and more efficient ways to go about things. These subtle things will remove some of the slight distractions that take away from your high-quality code. Again, great job here and congratulations!

**Comment by GoodMattwin** [comment]
Thank you!  I will work on the things you suggested.  I learned a ton on this course (not just the course materials, but understanding node, atom, etc. better) that I've got a lot to keep me busy :)
